# Generated by Django 3.1.13 on 2021-10-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_isbn"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="isbn",
            name="id",
        ),
        migrations.AlterField(
            model_name="isbn",
            name="code",
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
    ]
