# Generated by Django 3.1.13 on 2021-12-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_customer_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dog_set',
            field=models.ManyToManyField(blank=True, related_name='customers', to='dogs.Dog'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='dog_set',
            field=models.ManyToManyField(blank=True, related_name='owners', to='dogs.Dog'),
        ),
    ]
