# Generated by Django 3.1.13 on 2022-01-14 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0003_auto_20220114_0303"),
    ]

    operations = [
        migrations.AlterField(
            model_name="othertransaction",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="dogs.currency",
            ),
        ),
        migrations.AlterField(
            model_name="othertransaction",
            name="other_currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="dogs.othercurrency",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="dogs.currency",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="other_currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="dogs.othercurrency",
            ),
        ),
    ]
