# Generated by Django 4.0 on 2021-12-08 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_currency_transaction'),
        ('dogs', '0003_auto_20211205_0306'),
    ]

    operations = [
    ]
