# Generated by Django 3.1.13 on 2021-12-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_merge_20211208_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
