# Generated by Django 3.1.13 on 2021-12-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0006_auto_20211211_0023"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
