# Generated by Django 3.1.13 on 2021-10-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicCattle',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('sex', models.CharField(choices=[('C', 'Cow'), ('O', 'Ox'), ('B', 'Bull')], max_length=1)),
            ],
        ),
    ]
