# Generated by Django 3.1.13 on 2021-10-22 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0002_auto_20211022_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='readers.reader'),
        ),
    ]
