# Generated by Django 3.1.13 on 2021-11-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0003_auto_20211022_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='address_count',
            field=models.IntegerField(default=1),
        ),
    ]
