# Generated by Django 3.1.13 on 2021-11-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0004_reader_address_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='address_count',
        ),
        migrations.AddField(
            model_name='reader',
            name='total_city',
            field=models.FloatField(default=1),
        ),
    ]
