# Generated by Django 3.1.13 on 2021-11-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0005_auto_20211127_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='total_city',
        ),
        migrations.AddField(
            model_name='reader',
            name='latest_city',
            field=models.FloatField(default=1),
        ),
    ]
